### ISSUE TITLE
Scale duiring the evaluate

### ISSUE THREAD

**Issue by rsy6318** [microsoft/DualOctreeGNN#3]
Hi, 
I have run the code 
```
python dualocnn.py --config configs/shapenet_eval.yaml SOLVER.ckpt logs/shapenet/shapenet/checkpoints/00300.model.pth
```
and get the reconstructed meshes. I find that the mesh is in [-0.4,0.4]^2. Did you scale them into [-0.5,0.5]^2 during the evaluation (Table 1)?
And can we input the point cloud without noise?

**Comment by rsy6318** [comment]
Besides, I wonder what is the threshold of F-Score in Table 1. Is it 0.01 or 0.1?
Looking for your reply !

**Comment by wang-ps** [comment]
> I find that the mesh is in [-0.4,0.4]^2. Did you scale them into [-0.5,0.5]^2 during the evaluation (Table 1)?

No, please use the downloaded data in [-0.4, 04] for evaluation and the results of Table 1 can be reproduced directly. And in Table 1, all methods are trained and evaluated with the dataset we provided. It can be seen that the Chamfer distances of ConvONet and DeepMLS are smaller than the results in their papers, which is partially caused by the scale factor of [-0.4, 0.4].

> And can we input the point cloud without noise?

If the point cloud contains no noise, it is better to retrain the network without noise. Anyway, you can always forward the network trained with noisy point clouds, but the performance might decrease.

> Besides, I wonder what is the threshold of F-Score in Table 1. Is it 0.01 or 0.1?

In the `csv` file produced by the evaluation code we provided,  you can calculate the average of `f-score (mesh)`, which is the  `F-Score` reported in Table 1.

**Comment by rsy6318** [comment]
Thanks for your reply !
